# Generated by Django 4.2.1 on 2023-06-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_booking_date_alter_booking_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.FloatField(),
        ),
    ]
