# Generated by Django 4.2.1 on 2023-06-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_complaints'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='company',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
