# Generated by Django 4.2.1 on 2023-06-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_complaints_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='company',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
