# Generated by Django 4.2.1 on 2023-06-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_booking_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='send',
            field=models.BooleanField(default=False),
        ),
    ]
