# Generated by Django 4.2.1 on 2023-06-23 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectadmin', '0017_attendance'),
        ('customer', '0008_complaints_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projectadmin.products'),
        ),
    ]
