# Generated by Django 4.2.1 on 2023-06-23 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectadmin', '0017_attendance'),
        ('customer', '0009_booking_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='prodrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(max_length=500)),
                ('review', models.CharField(max_length=200)),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectadmin.products')),
            ],
        ),
    ]
