# Generated by Django 4.2.1 on 2023-06-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_prodrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='action',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaints',
            name='reply',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
