# Generated by Django 4.2.1 on 2023-07-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_complaints_action_complaints_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
