# Generated by Django 4.2.1 on 2023-05-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffname', models.CharField(max_length=20)),
                ('Phoneno', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=50)),
                ('Homename', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=20)),
                ('Location', models.CharField(max_length=50)),
                ('Pincode', models.CharField(max_length=50)),
                ('Photo', models.ImageField(upload_to='staff')),
                ('Password', models.CharField(max_length=20)),
                ('accept', models.BooleanField(default=False)),
                ('reject', models.BooleanField(default=False)),
            ],
        ),
    ]
