# Generated by Django 4.2.1 on 2023-06-22 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_attendence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='attendence',
        ),
    ]
