# Generated by Django 4.2.1 on 2023-07-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_delete_attendence'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='proof',
            field=models.ImageField(null=True, upload_to='staff'),
        ),
    ]
