# Generated by Django 4.2.1 on 2023-05-25 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='Comid',
        ),
    ]
