# Generated by Django 4.2.1 on 2023-06-16 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_company_comid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='Homename',
        ),
    ]
