# Generated by Django 4.2.1 on 2023-05-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('ptype', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('warranty', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='prod')),
                ('quantity', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=20)),
            ],
        ),
    ]
