# Generated by Django 4.2.1 on 2023-06-01 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectadmin', '0004_alter_products_ptype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='company',
        ),
        migrations.RemoveField(
            model_name='products',
            name='warranty',
        ),
    ]
