# Generated by Django 4.2.1 on 2023-06-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectadmin', '0005_remove_products_company_remove_products_warranty'),
    ]

    operations = [
        migrations.CreateModel(
            name='prod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('ptype', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=20)),
                ('quantity', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='company',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='warranty',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
