# Generated by Django 4.2.1 on 2023-06-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectadmin', '0006_prod_products_company_products_warranty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prod',
            name='desc',
        ),
        migrations.AlterField(
            model_name='prod',
            name='price',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
