# Generated by Django 4.2.1 on 2023-06-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectadmin', '0007_remove_prod_desc_alter_prod_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod',
            name='company',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
