# Generated by Django 4.2.1 on 2023-06-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectadmin', '0008_prod_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod',
            name='accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prod',
            name='reject',
            field=models.BooleanField(default=False),
        ),
    ]
