# Generated by Django 4.2.1 on 2023-06-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectadmin', '0009_prod_accept_prod_reject'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod',
            name='photo',
            field=models.ImageField(null=True, upload_to='prod'),
        ),
        migrations.AddField(
            model_name='prod',
            name='warranty',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
