# Generated by Django 4.2.1 on 2023-06-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectadmin', '0010_prod_photo_prod_warranty'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod',
            name='total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='prod',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='prod',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
