# Generated by Django 4.2.1 on 2023-06-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectadmin', '0011_prod_total_alter_prod_price_alter_prod_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
