# Generated by Django 4.2.1 on 2023-06-14 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectadmin', '0012_prod_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projectadmin.projectadmin'),
            preserve_default=False,
        ),
    ]
