# Generated by Django 4.2.1 on 2023-06-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectadmin', '0013_prod_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='products1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('ptype', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=20)),
                ('warranty', models.CharField(max_length=20)),
                ('photo', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='photo',
            field=models.ImageField(default='img', upload_to=''),
        ),
    ]
