# Generated by Django 4.2.1 on 2023-06-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectadmin', '0014_products1_alter_products_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='products1',
        ),
        migrations.AlterField(
            model_name='products',
            name='photo',
            field=models.CharField(max_length=200),
        ),
    ]
