# Generated by Django 4.2.1 on 2023-06-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectadmin', '0015_delete_products1_alter_products_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
