# Generated by Django 4.2.1 on 2023-06-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectadmin', '0016_alter_products_price_alter_products_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20, null=True)),
                ('staffs', models.CharField(max_length=20, null=True)),
                ('date', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
