# Generated by Django 4.2.1 on 2023-06-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectadmin', '0017_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='avgrate',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='rlength',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
