# Generated by Django 4.2.1 on 2023-06-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectadmin', '0018_products_avgrate_products_rlength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='rlength',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
