# Generated by Django 4.2.1 on 2023-06-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectadmin', '0019_alter_products_rlength'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='photo',
        ),
        migrations.AddField(
            model_name='products',
            name='Photo',
            field=models.ImageField(null=True, upload_to='products'),
        ),
    ]
