# Generated by Django 4.2.1 on 2023-06-29 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectadmin', '0020_remove_products_photo_products_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Photo',
            new_name='photo',
        ),
    ]
