# Generated by Django 4.2.1 on 2023-06-30 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectadmin', '0021_rename_photo_products_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='photo',
            new_name='Photo',
        ),
    ]
