# Generated by Django 4.2.1 on 2023-06-30 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectadmin', '0022_rename_photo_products_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Photo',
            new_name='photo',
        ),
    ]
