# Generated by Django 4.2.1 on 2023-06-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectadmin', '0023_rename_photo_products_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod',
            name='photo',
            field=models.ImageField(null=True, upload_to='products'),
        ),
    ]
