# Generated by Django 4.2.1 on 2023-06-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectadmin', '0024_alter_prod_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod',
            name='photo',
            field=models.ImageField(null=True, upload_to='prod'),
        ),
    ]
