# Generated by Django 4.2.1 on 2023-06-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectadmin', '0025_alter_prod_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='company',
        ),
        migrations.AlterField(
            model_name='products',
            name='photo',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
