# Generated by Django 4.2.1 on 2023-06-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectadmin', '0026_remove_products_company_alter_products_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='company',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
