# Generated by Django 4.2.1 on 2023-07-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectadmin', '0027_products_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod',
            name='deldate',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
