# Generated by Django 4.2.1 on 2023-07-12 05:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projectadmin', '0028_prod_deldate'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod',
            name='accdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='prod',
            name='orddate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='prod',
            name='deldate',
            field=models.DateField(null=True),
        ),
    ]
