# Generated by Django 4.2.1 on 2023-07-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectadmin', '0029_prod_accdate_prod_orddate_alter_prod_deldate'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
