# Generated by Django 4.2.1 on 2023-07-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectadmin', '0031_alter_products_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='warranty',
            field=models.CharField(max_length=200),
        ),
    ]
