# Generated by Django 4.2.1 on 2023-07-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectadmin', '0032_alter_products_warranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pname',
            field=models.CharField(max_length=500),
        ),
    ]
